### ISSUE TITLE
Jenkins can't clean workspace

### ISSUE THREAD

**Issue by Erikvv** [storj-thirdparty/uplink-php#17]
From Jenkins administrator:

> java.nio.file.FileSystemException: /var/lib/jenkins/workspace/uplink-php_PR-14_ws-cleanup_1635150122772/tmp/uplink-c/custommetadata.go: Operation not permitted

Probably I should try to run the container as non-root user.

**Comment by egonelbre** [comment]
See how https://github.com/storj/storj/blob/main/Jenkinsfile.public#L22 handles it.
