### ISSUE TITLE
README uplink version for composer

### ISSUE THREAD

**Issue by doge-lover** [storj-thirdparty/uplink-php#30]
There is a bug from 1.1.0 wherein excel/word document files' file format/extension gets corrupted which makes the excel file not openable which is fixed on 1.2.0 release. Had a bit of trouble sorting it out when other files are good to go when downloaded.

**Comment by Erikvv** [comment]
Thanks I'll tag 1.3.0 soon and update the readme

**Comment by Erikvv** [comment]
1.2.0 is now in the readme
