### ISSUE TITLE
how to get libuplink-AMD64-windows nt.so and fix failed loading issue? 

### ISSUE THREAD

**Issue by namen3645** [storj-thirdparty/uplink-php#31]
Failed loading 'C:\OpenServer\domains\s3storj.loc\vendor\storj\uplink/build/libuplink-AMD64-windows nt.so

i need libuplink-AMD64-windows nt.so but google | github | duck duck go can't find this packege

**Comment by Erikvv** [comment]
@namen3645 Windows support will be in the next release v1.3.0

@sammosna  a better error message will be in the next release v1.3.0 to help diagnose such issues.
