### ISSUE TITLE
Issue while setting up composer on windows

### ISSUE THREAD

**Issue by nehakjain2005** [storj-thirdparty/uplink-php#41]
While setting up this library on windows I am getting issue. I already have php_ffi.dll and php 7.4.26 version. Still it says its missing. Please help

    - Root composer.json requires storj/uplink ^1.3 -> satisfiable by storj/uplink[1.3.0].
    - storj/uplink 1.3.0 requires ext-ffi * -> it is missing from your system. Install or enable PHP's ffi extension.

**Comment by Erikvv** [comment]
Did you enable the extension in php.ini?

```
extension=ffi
```

**Comment by nehakjain2005** [comment]
yes I have done that

**Comment by Erikvv** [comment]
I tested with PHP 7.4.26 on Windows and it works. 

Probably you have something wrong in your php config. 

Some ideas to help diagnose the issue:

- Check `php.exe --ini` that the correct ini files are loaded 
- Check `php.exe -r "phpinfo();"` that the modules are loaded 
- Check `php.exe -r "phpinfo();"` that warnings are enabled
  - display_errors => STDOUT
  - display_startup_errors => On
  - error_reporting => 32767

**Comment by Erikvv** [comment]
I close this issue because I don't see how I can improve this. Just too many ways to install PHP for me to address every OS and installation method. Suggestions welcome though. I hope you get it fixed up.
