### ISSUE TITLE
Return Share URL after upload

### ISSUE THREAD

**Issue by arifals27** [storj-thirdparty/uplink-php#48]
Hi
Thank you for you lib.

But, Can you add some feature, after upload image, it will return "share url" to access that image.

Thank you again.

**Comment by Erikvv** [comment]
This feature exists.

This is the function: https://github.com/storj-thirdparty/uplink-php/blob/264b074f830f69e6d2a6fb9c442f35d3b1b7c10b/src/Edge/Edge.php#L84
